### ISSUE TITLE
Django Project File

### ISSUE THREAD

**Issue by Aliflail** [Aliflail/MiniProject#1]
Hey Every one,
we have very short time to build our project. We have to finish it by the end of this month. its deployment nest month . So we barely have 3 weeks. In this new repository, push only those of django project files.
Since we all have our own work to do , stick to the plan. finish your work and push to this repository when ever error free update is done.
Lets Fire the Engine!!!
Start working. we have a lot of free time from now. dont waste the time and start working.!

Alif

**Comment by albinpaul** [comment]
i think we already did it
